### ISSUE TITLE
Slight Readability issues with unresolved links

### ISSUE THREAD

**Issue by sigrunixia** [dbarenholz/halcyon-obsidian#2]
The dashes, particularly on smaller screens, do make the text blend together and a little more fuzzy/hard to read.

![CleanShot 2023-10-02 at 11 20 15@2x](https://github.com/dbarenholz/halcyon-obsidian/assets/68425372/a8eae624-28f0-45e6-afce-c2179d6a28a6)

**Comment by dbarenholz** [comment]
I have added the following into the base-theme as a side-effect from fixing #4 .

```css
body.theme-dark {
	text-underline-offset: 0.1em;
}
```

@sigrunixia If you believe this suffices (I can't really see the hard-to-read-ness so it's hard to evaluate myself), go ahead and close the issue. Otherwise, eventually this will be addressable with Style Settings as an option to make it a normal underline.

**Comment by sigrunixia** [comment]
It is quite a bit better. It's now clear that the words won't blur into the underline. :)
